packages:
  - '.'

allowBuilds:
  gifsicle: set this to true or false
  hexo-util: set this to true or false
  jpegtran-bin: set this to true or false
  mozjpeg: set this to true or false
  optipng-bin: set this to true or false
  pngquant-bin: set this to true or false

onlyBuiltDependencies:
  - gifsicle
  - hexo-util
  - jpegtran-bin
  - mozjpeg
  - optipng-bin
  - pngquant-bin
